name: Node.js CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.0
      - name: Intall Dependencies
        run: npm install
      - name: Execute lint
        run: npm run lint
